name: Deploy Backend

on:
  push:
    branches: [deploy-with-sanity]
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change directory to backend
        run: cd backend

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npm run deploy

      - name: Deploy graphql
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npm run deploy-graphql
