name: Deploy Backend
on:
  push:
    branches: [deploy-with-sanity]
    paths:
      - backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
      - name: Build Backend
        run: |
          npm run build
      - name: Deploy Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          npm run deploy
      - name: Deploy GraphQL API
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          npm run deploy-graphql
